pg_version: 12
data_dir: /var/lib/postgresql/data
pgdata_dir: "{{ data_dir }}/pgdata"
postgres_password: "5HP3sU4Lcw7JTtJ"
replication_user: replica
replication_password: "5HP3sU4Lcw7JTtJ"
app_user: dob_api_user
app_password: "TkmP8qLox6sCy3o"
app_db: dob_api_db
block_device: /dev/nvme1n1
primary_private_ip: 10.0.1.233
replica_private_ip: 10.0.1.213
primary_dr_private_ip: 10.1.1.23
replica_dr_private_ip: 10.1.1.253
prometheus_user: prometheus
alertmanager_user: alertmanager
postgres_exporter_version: "0.11.0"
prometheus_version: "2.50.0"
alertmanager_version: "0.25.0"
alert_email_recipient: "loukas.prevyzis@outlook.com"
alert_email_sender: "loukas.prevyzis@outlook.com"
smtp_server: "smtp.office365.com"
smtp_port: 587
smtp_user: "loukas.prevyzis@outlook.com"
smtp_password: ""
prometheus_scrape_targets:
  - "{{ primary_private_ip }}:9187"
  - "{{ replica_private_ip }}:9187"
  - "{{ primary_dr_private_ip }}:9187"
  - "{{ replica_dr_private_ip }}:9187"
postgres_backup_bucket_primary: "dob-api-postgres-backups" # S3 bucket for primary region backups in eu-west-1
postgres_backup_bucket_dr: "dob-api-postgres-backups" #same bucket name in eu-central-1 (DR) for simplicity
s3_bucket_map:
  postgres_primary: "{{ postgres_backup_bucket_primary }}"
  postgres_primary_dr: "{{ postgres_backup_bucket_dr }}"
  postgres_replicas: "{{ postgres_backup_bucket_primary }}"
  postgres_replicas_dr: "{{ postgres_backup_bucket_dr }}"
ecs_cluster_name: dob_api-cluster
ecs_service_name: dob-api-service
task_definition_family: dob-api-task
container_name: dob-api