
- include_tasks: primary.yml
  when: "'postgres_primary' in group_names"

- include_tasks: replica.yml
  when: "'postgres_replicas' in group_names"

- include_tasks: primary-dr.yml
  when: "'postgres_primary_dr' in group_names"

- include_tasks: replica-dr.yml
  when: "'postgres_replicas_dr' in group_names"

- include_tasks: db-backup.yml

- include_tasks: monitoring.yml
  when: "'postgres_primary' in group_names or 'postgres_replicas' in group_names or 'postgres_primary_dr' in group_names or 'postgres_replicas_dr' in group_names"

- include_tasks: promote-dr.yml
  when: "'postgres_primary_dr' in group_names and 'postgres_replicas_dr' in group_names"