name: dob-api CI/CD

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

env:
  TF_VERSION: 1.5.7
  TF_WORKSPACE_PRIMARY: prod-primary
  TF_WORKSPACE_SECONDARY: prod-secondary

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Select Terraform Workspace
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            terraform workspace select $TF_WORKSPACE_PRIMARY || terraform workspace new $TF_WORKSPACE_PRIMARY
          else
            terraform workspace select $TF_WORKSPACE_SECONDARY || terraform workspace new $TF_WORKSPACE_SECONDARY
          fi
        working-directory: infra

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/develop'
        run: terraform plan -input=false -out=tfplan
        working-directory: infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: infra