- name: Setup PostgreSQL primary (main region)
  hosts: postgres_primary
  become: true
  roles:
    - postgres

- name: Setup PostgreSQL replica (main region)
  hosts: postgres_replicas
  become: true
  roles:
    - { role: postgres, tasks_from: replica.yml }

- name: Setup PostgreSQL primary (DR region)
  hosts: postgres_primary_dr
  become: true
  roles:
    - { role: postgres, tasks_from: primary-dr.yml }

- name: Setup PostgreSQL replica (DR region)
  hosts: postgres_replicas_dr
  become: true
  roles:
    - { role: postgres, tasks_from: replica-dr.yml }

- name: Setup PostgreSQL backup and WAL archiving
  hosts: postgres_primary
  become: true
  roles:
    - { role: postgres, tasks_from: db-backup.yml }

- name: Setup PostgreSQL backup and WAL archiving on DR primary
  hosts: postgres_primary_dr
  become: true
  roles:
    - { role: postgres, tasks_from: db-backup.yml }

- name: Setup PostgreSQL monitoring (Primary Region DBs)
  hosts:
    - postgres_primary
    - postgres_replicas
  become: true
  roles:
    - { role: postgres, tasks_from: monitoring.yml }

- name: Setup PostgreSQL monitoring (DR Region DBs)
  hosts:
    - postgres_primary_dr
    - postgres_replicas_dr
  become: yes
  roles:
    - { role: postgres, tasks_from: monitoring.yml }